"""pysnmp output formatter.

Generates a Python module that can be loaded by pysnmp\'s MibBuilder.
The output closely follows the format used by pysmi-compiled MIBs:

    mibBuilder.importSymbols(\'SNMPv2-SMI\', \'ModuleIdentity\', ...)
    ifMIB = ModuleIdentity((1, 3, 6, 1, 2, 1, 31,))
    mibBuilder.exportSymbols(\'IF-MIB\', **{\'ifMIB\': ifMIB, ...})

pysnmp object-class mapping
----------------------------

    OBJECT-TYPE syntax            pysnmp class
    ------------------------------------------
    SEQUENCE OF <X>               MibTable
    Named type → SEQUENCE in      MibTableRow
      module.types
    Everything else               MibScalar

MibTableColumn detection requires knowing which OID is the parent row.
This needs full OID tree resolution (resolver/ phase), which is not
available to the formatter. Scalars are emitted as MibScalar; a
post-processing pass after OID resolution can upgrade them.

Known limitations (each annotated with TODO in generated output):
- TEXTUAL-CONVENTION constraints not fully emitted.
- NOTIFICATION-TYPE OBJECTS clause omitted.
- SEQUENCE / CHOICE types generate a placeholder comment.

Output file: {output_dir}/{ModuleName}.py
"""
from __future__ import annotations

from jinja2 import BaseLoader, Environment

from trishul_smi.models.mib_module import MibModule
from trishul_smi.models.mib_object import MibObject

# ---------------------------------------------------------------------------
# Object-class detection
# ---------------------------------------------------------------------------

def _pysnmp_obj_class(obj: MibObject, module: MibModule) -> str:
    """Return the correct pysnmp constructor class name for *obj*.

    Resolution order (first match wins):
    1. syntax starts with ``SEQUENCE OF`` → MibTable (the table object itself)
    2. syntax is a named type that resolves to SEQUENCE in this module's types
       → MibTableRow (the row object)
    3. Everything else → MibScalar
       (MibTableColumn needs OID-tree resolution — see module docstring)
    """
    syntax = (obj.syntax or "").strip()
    if syntax.upper().startswith("SEQUENCE OF"):
        return "MibTable"
    if syntax and syntax in module.types:
        base = (module.types[syntax].base_type or "").upper()
        if base.startswith("SEQUENCE"):
            return "MibTableRow"
    return "MibScalar"


# ---------------------------------------------------------------------------
# Jinja2 template
# ---------------------------------------------------------------------------

_TEMPLATE = """\
# {{ module.name }} MIB module
# Generated by trishul-smi  —  do not edit by hand.
# Source dialect: {{ module.language }}

from pysnmp.smi.builder import MibBuilder

mibBuilder = MibBuilder()

# --- Always-available pysnmp builtins ---------------------------------
# Mirrors what pysmi-compiled MIBs unconditionally import so that
# NotificationType, TextualConvention, etc. never raise NameError when
# pysnmp loads this module, even if the source MIB omits their imports.
( ModuleIdentity, ObjectType, NotificationType,
  MibScalar, MibTable, MibTableRow, MibTableColumn,
  MibIdentifier, ObjectIdentity, Integer32, OctetString,
  IpAddress, Counter32, Counter64, Gauge32, Unsigned32,
  TimeTicks, Opaque, Bits, ) = mibBuilder.importSymbols(
    'SNMPv2-SMI',
    'ModuleIdentity', 'ObjectType', 'NotificationType',
    'MibScalar', 'MibTable', 'MibTableRow', 'MibTableColumn',
    'MibIdentifier', 'ObjectIdentity', 'Integer32', 'OctetString',
    'IpAddress', 'Counter32', 'Counter64', 'Gauge32', 'Unsigned32',
    'TimeTicks', 'Opaque', 'Bits',
)
( TextualConvention, ) = mibBuilder.importSymbols(
    'SNMPv2-TC', 'TextualConvention',
)
# ObjectIdentifier is the ASN.1 OID value type (SYNTAX OBJECT IDENTIFIER).
# It lives in the 'ASN1' module — distinct from MibIdentifier (SNMPv2-SMI)
# which is used for OID *nodes* in the MIB tree, not SYNTAX value types.
( ObjectIdentifier, ) = mibBuilder.importSymbols('ASN1', 'ObjectIdentifier')

# --- MIB-specific imports ----------------------------------------------
{% for from_module, symbols in module.imports.items() %}
{{ symbols | map_pysnmp_assign(from_module) }}
{% endfor %}

# --- MODULE-IDENTITY / OBJECT-IDENTITY --------------------------------
{% for name, obj in module.objects.items() if obj.object_type in (
       'MODULE-IDENTITY', 'OBJECT-IDENTITY', 'OBJECT IDENTIFIER') %}
{{ name | pyid }} = {{ obj.object_type | pysnmp_class_for_type }}(
    {{ obj.oid_path | oid_tuple }}
)
{% if obj.status %}if mibBuilder.loadTexts: {{ name | pyid }}.setStatus('{{ obj.status }}')
{% endif %}
{% if obj.description %}if mibBuilder.loadTexts: {{ name | pyid }}.setDescription(
    \"\"\"{{ obj.description | indent(4) }}\"\"\"
)
{% endif %}
{% endfor %}

# --- OBJECT-TYPE ------------------------------------------------------
{% for name, obj, cls in objects_with_class %}
{{ name | pyid }} = {{ cls }}(
    {{ obj.oid_path | oid_tuple }},
    {{ obj.syntax | pysnmp_syntax }}
).setMaxAccess('{{ obj.max_access or 'read-only' }}')
{% if obj.status %}if mibBuilder.loadTexts: {{ name | pyid }}.setStatus('{{ obj.status }}')
{% endif %}
{% if obj.description %}if mibBuilder.loadTexts: {{ name | pyid }}.setDescription(
    \"\"\"{{ obj.description | indent(4) }}\"\"\"
)
{% endif %}
{% endfor %}

# --- NOTIFICATION-TYPE ------------------------------------------------
{% for name, notif in module.notifications.items() %}
{{ name | pyid }} = NotificationType(
    {{ notif.oid_path | oid_tuple }}
)  # TODO: add .setObjects() from OBJECTS clause
{% if notif.status %}if mibBuilder.loadTexts: {{ name | pyid }}.setStatus('{{ notif.status }}')
{% endif %}
{% endfor %}

# --- TEXTUAL-CONVENTION -----------------------------------------------
{% for name, tc in module.types.items() %}
{{ name }} = TextualConvention  # base: {{ tc.base_type }}
# TODO: emit full TC definition (DisplayHint, constraints)
{% endfor %}

# --- Export -----------------------------------------------------------
mibBuilder.exportSymbols(
    '{{ module.name }}',
{% for name in module.objects %}    **{'{{ name }}': {{ name | pyid }}},
{% endfor %}
{% for name in module.types %}    **{'{{ name }}': {{ name }}},
{% endfor %}
)
"""

# ---------------------------------------------------------------------------
# Jinja2 filters
# ---------------------------------------------------------------------------

_PYSNMP_CLASS_FOR_TYPE = {
    "MODULE-IDENTITY":   "ModuleIdentity",
    "OBJECT-IDENTITY":   "ObjectIdentity",
    "OBJECT IDENTIFIER": "MibIdentifier",
    "NOTIFICATION-TYPE": "NotificationType",
    "TRAP-TYPE":         "NotificationType",
}

_PYSNMP_SYNTAX = {
    "INTEGER":           "Integer32()",
    "Integer32":         "Integer32()",
    "OCTET STRING":      "OctetString()",
    # ObjectIdentifier here is the ASN.1 value type imported above from 'ASN1'.
    # MibIdentifier (SNMPv2-SMI) is for OID tree *nodes*, not SYNTAX values.
    "OBJECT IDENTIFIER": "ObjectIdentifier()",
    "IpAddress":         "IpAddress()",
    "Counter32":         "Counter32()",
    "Counter64":         "Counter64()",
    "Gauge32":           "Gauge32()",
    "Unsigned32":        "Unsigned32()",
    "TimeTicks":         "TimeTicks()",
    "Opaque":            "Opaque()",
    "BITS":              "Bits()",
}


def _pyid(name: str) -> str:
    """Replace hyphens with underscores — hyphens are invalid in Python identifiers."""
    return name.replace("-", "_")


def _oid_tuple(oid_path: list[int]) -> str:
    if not oid_path:
        return "()"
    return "(" + ", ".join(str(n) for n in oid_path) + ",)"


def _pysnmp_class_for_type(object_type: str) -> str:
    return _PYSNMP_CLASS_FOR_TYPE.get(object_type, "MibIdentifier")


def _pysnmp_syntax(syntax: str | None) -> str:
    """Map a MIB syntax string to a pysnmp constructor call.

    Fallback rules (in order):
    1. None / empty  → OctetString() with comment
    2. Exact match in _PYSNMP_SYNTAX  → mapped value
    3. Contains spaces or is not a valid Python identifier (e.g. "OCTET STRING",
       "SEQUENCE OF ifEntry") → OctetString() with a TODO comment.
       Plain f"{syntax}()" would emit broken Python for any spaced token.
    4. Single hyphenated word → safe identifier + ()
    """
    if not syntax:
        return "OctetString()  # unknown syntax"
    mapped = _PYSNMP_SYNTAX.get(syntax)
    if mapped:
        return mapped
    safe = syntax.replace("-", "_")
    if " " in safe or not safe.isidentifier():
        return f"OctetString()  # TODO: map syntax '{syntax}'"
    return f"{safe}()"


def _map_pysnmp_assign(symbols: list[str], from_module: str) -> str:
    """Render: ( Sym1, Sym2, ) = mibBuilder.importSymbols('MOD', 'Sym1', 'Sym2')"""
    if not symbols:
        return ""
    sym_py = ", ".join(_pyid(s) for s in symbols)
    sym_str = ", ".join(f"'{s}'" for s in symbols)
    return f"( {sym_py}, ) = mibBuilder.importSymbols('{from_module}', {sym_str})"


# ---------------------------------------------------------------------------
# Formatter class
# ---------------------------------------------------------------------------

def _make_env() -> Environment:
    env = Environment(loader=BaseLoader(), keep_trailing_newline=True)
    env.filters["pyid"] = _pyid
    env.filters["oid_tuple"] = _oid_tuple
    env.filters["pysnmp_class_for_type"] = _pysnmp_class_for_type
    env.filters["pysnmp_syntax"] = _pysnmp_syntax
    env.filters["map_pysnmp_assign"] = _map_pysnmp_assign
    return env


class PysnmpFormatter:
    """Renders a MibModule as a pysnmp-compatible Python module."""

    FILE_SUFFIX = ".py"

    def __init__(self) -> None:
        self._env = _make_env()
        self._tmpl = self._env.from_string(_TEMPLATE)

    def format(self, module: MibModule) -> str:  # noqa: A003
        objects_with_class = [
            (name, obj, _pysnmp_obj_class(obj, module))
            for name, obj in module.objects.items()
            if obj.object_type == "OBJECT-TYPE"
        ]
        return self._tmpl.render(module=module, objects_with_class=objects_with_class)
