"""pysnmp output formatter — best-effort, frozen.

This formatter is not actively developed. For production pysnmp output use
pysmi (https://github.com/lextudio/pysmi), which is maintained by the pysnmp
ecosystem. This module is kept for convenience only and will not track pysmi
feature changes.

Generates a Python module that can be loaded by pysnmp\'s MibBuilder.

Output file: {output_dir}/{ModuleName}.py
"""

from __future__ import annotations

from typing import Any

from jinja2 import BaseLoader, Environment

from trishul_smi.models.mib_module import MibModule
from trishul_smi.models.mib_object import MibObject

# ---------------------------------------------------------------------------
# Object-class detection
# ---------------------------------------------------------------------------


def _pysnmp_obj_class(
    obj: MibObject,
    module: MibModule,
    oid_to_class: dict[tuple[int, ...], str] | None = None,
) -> str:
    """Return the correct pysnmp constructor class name for *obj*.

    Resolution order (first match wins):
    1. syntax starts with ``SEQUENCE OF`` → MibTable (the table object itself)
    2. syntax is a named type that resolves to SEQUENCE in this module's types
       → MibTableRow (the row object)
    3. parent OID in oid_to_class resolves to MibTableRow → MibTableColumn
    4. Everything else → MibScalar
    """
    syntax = (obj.syntax or "").strip()
    if syntax.upper().startswith("SEQUENCE OF"):
        return "MibTable"
    if syntax and syntax in module.types:
        base = (module.types[syntax].base_type or "").upper()
        if base.startswith("SEQUENCE"):
            return "MibTableRow"
    if oid_to_class is not None and obj.oid_path:
        parent_key = tuple(obj.oid_path[:-1])
        if oid_to_class.get(parent_key) == "MibTableRow":
            return "MibTableColumn"
    return "MibScalar"


# ---------------------------------------------------------------------------
# Jinja2 template
# ---------------------------------------------------------------------------

_TEMPLATE = """\
# {{ module.name }} MIB module
# Generated by trishul-smi  —  do not edit by hand.
# Source dialect: {{ module.language }}

if 'mibBuilder' not in globals():
    import sys
    sys.stderr.write(__doc__)
    sys.exit(1)

# --- Always-available pysnmp builtins ---------------------------------
# Mirrors what pysmi-compiled MIBs unconditionally import so that
# NotificationType, TextualConvention, etc. never raise NameError when
# pysnmp loads this module, even if the source MIB omits their imports.
( ModuleIdentity, ObjectType, NotificationType,
  MibScalar, MibTable, MibTableRow, MibTableColumn,
  MibIdentifier, ObjectIdentity, Integer32, OctetString,
  IpAddress, Counter32, Counter64, Gauge32, Unsigned32,
  TimeTicks, Opaque, Bits, ) = mibBuilder.importSymbols(
    'SNMPv2-SMI',
    'ModuleIdentity', 'ObjectType', 'NotificationType',
    'MibScalar', 'MibTable', 'MibTableRow', 'MibTableColumn',
    'MibIdentifier', 'ObjectIdentity', 'Integer32', 'OctetString',
    'IpAddress', 'Counter32', 'Counter64', 'Gauge32', 'Unsigned32',
    'TimeTicks', 'Opaque', 'Bits',
)
( TextualConvention, ) = mibBuilder.importSymbols(
    'SNMPv2-TC', 'TextualConvention',
)
# ObjectIdentifier is the ASN.1 OID value type (SYNTAX OBJECT IDENTIFIER).
# It lives in the 'ASN1' module — distinct from MibIdentifier (SNMPv2-SMI)
# which is used for OID *nodes* in the MIB tree, not SYNTAX value types.
( ObjectIdentifier, ) = mibBuilder.importSymbols('ASN1', 'ObjectIdentifier')
( ValueSizeConstraint, ValueRangeConstraint, SingleValueConstraint,
  ConstraintsUnion, ) = mibBuilder.importSymbols(
    'ASN1-REFINEMENT',
    'ValueSizeConstraint', 'ValueRangeConstraint', 'SingleValueConstraint',
    'ConstraintsUnion',
)

# --- MIB-specific imports ----------------------------------------------
{% for from_module, symbols in module.imports.items() %}
{{ symbols | map_pysnmp_assign(from_module) }}
{% endfor %}

# --- MODULE-IDENTITY / OBJECT-IDENTITY / MIB STRUCTURE ---------------
{% for name, obj in module.objects.items() if obj.object_type in (
       'MODULE-IDENTITY', 'OBJECT-IDENTITY', 'OBJECT IDENTIFIER',
       'OBJECT-GROUP', 'NOTIFICATION-GROUP', 'MODULE-COMPLIANCE', 'AGENT-CAPABILITIES') %}
{{ name | pyid }} = {{ obj.object_type | pysnmp_class_for_type }}(
    {{ obj.oid_path | oid_tuple }}
)
{% if not no_texts and obj.status %}if mibBuilder.loadTexts: {{ name | pyid }}.setStatus('{{ obj.status }}')
{% endif %}
{% if not no_texts and obj.description %}if mibBuilder.loadTexts: {{ name | pyid }}.setDescription(
    \"\"\"{{ obj.description | indent(4) }}\"\"\"
)
{% endif %}
{% if not no_texts and obj.object_type == 'MODULE-IDENTITY' and module.organization %}if mibBuilder.loadTexts: {{ name | pyid }}.setOrganization(
    \"\"\"{{ module.organization | indent(4) }}\"\"\"
)
{% endif %}
{% if not no_texts and obj.object_type == 'MODULE-IDENTITY' and module.revisions %}if mibBuilder.loadTexts: {{ name | pyid }}.setRevisions(
    ({% for r in module.revisions %}'{{ r.date }}', {% endfor %})
)
{% endif %}
{% endfor %}

# --- OBJECT-TYPE syntax wrappers (constrained inline types) -----------
{% for name, obj, cls in objects_with_class if obj.constraints %}
class _{{ name | pyid }}_Type({{ obj.syntax | pysnmp_syntax_class }}):
    subtypeSpec = {{ obj.syntax | pysnmp_syntax_class }}.subtypeSpec
    subtypeSpec += ConstraintsUnion(
        {{ obj.constraints | tc_subtypespec }},
    )

_{{ name | pyid }}_Type.__name__ = "{{ obj.syntax }}"
{% endfor %}

# --- OBJECT-TYPE ------------------------------------------------------
{% for name, obj, cls in objects_with_class %}
{% if cls in ('MibTable', 'MibTableRow') %}{{ name | pyid }} = {{ cls }}(
    {{ obj.oid_path | oid_tuple }}
).setMaxAccess('{{ obj.max_access or 'read-only' }}'){% else %}{{ name | pyid }} = {{ cls }}(
    {{ obj.oid_path | oid_tuple }},
    {% if obj.constraints %}_{{ name | pyid }}_Type(){% else %}{{ obj.syntax | pysnmp_syntax }}{% endif %}
).setMaxAccess('{{ obj.max_access or 'read-only' }}'){% endif %}
{% if not no_texts and obj.status %}if mibBuilder.loadTexts: {{ name | pyid }}.setStatus('{{ obj.status }}')
{% endif %}
{% if not no_texts and obj.description %}if mibBuilder.loadTexts: {{ name | pyid }}.setDescription(
    \"\"\"{{ obj.description | indent(4) }}\"\"\"
)
{% endif %}
{% if obj.index %}{{ name | pyid }}.setIndexNames(
{%- for idx in obj.index %}
    (0, '{{ module.name }}', '{{ idx }}'),
{%- endfor %}
)
{% endif %}
{% if obj.augments %}{{ name | pyid }}.setIndexNames(*{{ obj.augments | pyid }}.getIndexNames())
{% endif %}
{% endfor %}

# --- NOTIFICATION-TYPE ------------------------------------------------
{% for name, notif in module.notifications.items() %}
{{ name | pyid }} = NotificationType(
    {{ notif.oid_path | oid_tuple }}
)
{% if notif.members %}{{ name | pyid }}.setObjects(
{%- for m in notif.members %}
    ('{{ m | member_module(module.name, name_to_mod) }}', '{{ m }}'),
{%- endfor %}
)
{% endif %}
{% if not no_texts and notif.status %}if mibBuilder.loadTexts: {{ name | pyid }}.setStatus('{{ notif.status }}')
{% endif %}
{% if not no_texts and notif.description %}if mibBuilder.loadTexts: {{ name | pyid }}.setDescription(
    \"\"\"{{ notif.description | indent(4) }}\"\"\"
)
{% endif %}
{% endfor %}

# --- TEXTUAL-CONVENTION -----------------------------------------------
{% for name, tc in module.types.items() if not tc.base_type.upper().startswith('SEQUENCE') and not tc.base_type.upper().startswith('CHOICE') %}
class {{ name }}(TextualConvention, {{ tc.base_type | pysnmp_syntax_class }}):
{% if tc.display_hint %}    displayHint = "{{ tc.display_hint }}"
{% endif %}
{% if tc.status %}    status = '{{ tc.status }}'
{% endif %}
{% if not no_texts and tc.description %}    if mibBuilder.loadTexts: description = \"\"\"{{ tc.description | indent(4) }}\"\"\"
{% endif %}
{% if tc.constraints %}    subtypeSpec = {{ tc.base_type | pysnmp_syntax_class }}.subtypeSpec
    subtypeSpec += ConstraintsUnion(
        {{ tc.constraints | tc_subtypespec }},
    )
{% endif %}
{% if not tc.display_hint and not tc.status and not tc.description and not tc.constraints %}    pass
{% endif %}
{% endfor %}

# --- Export -----------------------------------------------------------
mibBuilder.exportSymbols(
    '{{ module.name }}',
    **{
{%- for name in module.objects %}
        '{{ name }}': {{ name | pyid }},
{%- endfor %}
{%- for name in module.notifications %}
        '{{ name }}': {{ name | pyid }},
{%- endfor %}
{%- for name, tc in module.types.items() if not tc.base_type.upper().startswith('SEQUENCE') and not tc.base_type.upper().startswith('CHOICE') %}
        '{{ name }}': {{ name }},
{%- endfor %}
    }
)
"""

# ---------------------------------------------------------------------------
# Jinja2 filters
# ---------------------------------------------------------------------------

# Maps SMI macro keyword → pysnmp constructor class name.
_PYSNMP_CLASS_FOR_TYPE = {
    "MODULE-IDENTITY": "ModuleIdentity",
    "OBJECT-IDENTITY": "ObjectIdentity",
    "OBJECT IDENTIFIER": "MibIdentifier",
    "NOTIFICATION-TYPE": "NotificationType",
    "TRAP-TYPE": "NotificationType",
    "OBJECT-GROUP": "ObjectGroup",
    "NOTIFICATION-GROUP": "NotificationGroup",
    "MODULE-COMPLIANCE": "ModuleCompliance",
    "AGENT-CAPABILITIES": "AgentCapabilities",
}

# SMIv2-CONF symbols: MIB source name → pysnmp exported Python name.
# pysnmp's SNMPv2-CONF exports class names, not the hyphenated macro keywords.
_SNMPV2_CONF_NAME_MAP: dict[str, str] = {
    "OBJECT-GROUP": "ObjectGroup",
    "NOTIFICATION-GROUP": "NotificationGroup",
    "MODULE-COMPLIANCE": "ModuleCompliance",
    "AGENT-CAPABILITIES": "AgentCapabilities",
}

_PYSNMP_SYNTAX = {
    "INTEGER": "Integer32()",
    "Integer32": "Integer32()",
    "OCTET STRING": "OctetString()",
    # ObjectIdentifier here is the ASN.1 value type imported above from 'ASN1'.
    # MibIdentifier (SNMPv2-SMI) is for OID tree *nodes*, not SYNTAX values.
    "OBJECT IDENTIFIER": "ObjectIdentifier()",
    "IpAddress": "IpAddress()",
    "Counter32": "Counter32()",
    "Counter64": "Counter64()",
    "Gauge32": "Gauge32()",
    "Unsigned32": "Unsigned32()",
    "TimeTicks": "TimeTicks()",
    "Opaque": "Opaque()",
    "BITS": "Bits()",
}


def _pyid(name: str) -> str:
    """Replace hyphens with underscores — hyphens are invalid in Python identifiers."""
    return name.replace("-", "_")


def _oid_tuple(oid_path: list[int]) -> str:
    if not oid_path:
        return "()"
    return "(" + ", ".join(str(n) for n in oid_path) + ",)"


def _pysnmp_class_for_type(object_type: str) -> str:
    return _PYSNMP_CLASS_FOR_TYPE.get(object_type, "MibIdentifier")


def _pysnmp_syntax(syntax: str | None) -> str:
    """Map a MIB syntax string to a pysnmp constructor call.

    Fallback rules (in order):
    1. None / empty  → OctetString() with comment
    2. Exact match in _PYSNMP_SYNTAX  → mapped value
    3. Contains spaces or is not a valid Python identifier (e.g. "OCTET STRING",
       "SEQUENCE OF ifEntry") → OctetString() with a TODO comment.
       Plain f"{syntax}()" would emit broken Python for any spaced token.
    4. Single hyphenated word → safe identifier + ()
    """
    if not syntax:
        return "OctetString()  # unknown syntax"
    mapped = _PYSNMP_SYNTAX.get(syntax)
    if mapped:
        return mapped
    safe = syntax.replace("-", "_")
    if " " in safe or not safe.isidentifier():
        return f"OctetString()  # TODO: map syntax '{syntax}'"
    return f"{safe}()"


def _map_pysnmp_assign(symbols: list[str], from_module: str) -> str:
    """Render: ( Sym1, Sym2, ) = mibBuilder.importSymbols('MOD', 'Sym1', 'Sym2')"""
    if not symbols:
        return ""
    # SNMPv2-CONF is the only module where the SMI macro keyword names differ from
    # what pysnmp actually exports (e.g. MIB source says OBJECT-GROUP, but pysnmp's
    # SNMPv2-CONF exports ObjectGroup).  All other modules export exactly what the
    # MIB source names in its IMPORTS clause, so _pyid (hyphen → underscore) is enough.
    name_map = _SNMPV2_CONF_NAME_MAP if from_module == "SNMPv2-CONF" else {}
    py_names = [name_map.get(s, _pyid(s)) for s in symbols]
    export_names = [name_map.get(s, s) for s in symbols]
    sym_py = ", ".join(py_names)
    sym_str = ", ".join(f"'{n}'" for n in export_names)
    return f"( {sym_py}, ) = mibBuilder.importSymbols('{from_module}', {sym_str})"


# Maps MIB base_type strings to the pysnmp class name used as a TC mixin.
_SYNTAX_TO_CLASS: dict[str, str] = {
    "INTEGER": "Integer32",
    "Integer32": "Integer32",
    "OCTET STRING": "OctetString",
    "OBJECT IDENTIFIER": "ObjectIdentifier",
    "IpAddress": "IpAddress",
    "Counter32": "Counter32",
    "Counter64": "Counter64",
    "Gauge32": "Gauge32",
    "Unsigned32": "Unsigned32",
    "TimeTicks": "TimeTicks",
    "Opaque": "OctetString",
    "BITS": "Bits",
    "NetworkAddress": "OctetString",
}


def _pysnmp_syntax_class(base_type: str) -> str:
    """Map a MIB base_type to the pysnmp class used in a TC class definition."""
    mapped = _SYNTAX_TO_CLASS.get(base_type)
    if mapped:
        return mapped
    safe = base_type.replace("-", "_")
    if " " in safe or not safe.isidentifier():
        return "OctetString"
    return safe


def _tc_subtypespec(constraints: dict[str, Any]) -> str:
    """Convert a constraints dict to a pysnmp subtypeSpec expression."""
    kind = constraints.get("kind", "")
    data = constraints.get("data", [])

    if kind == "size":
        return _range_expr(data, "ValueSizeConstraint")
    if kind == "range":
        return _range_expr(data, "ValueRangeConstraint")
    if kind in ("enum", "bits"):
        values = [str(item[1]) for item in data if isinstance(item, list)]
        return f"SingleValueConstraint({', '.join(values)})"
    if kind == "union":
        parts = [_tc_subtypespec(m) for m in data]
        return f"ConstraintsUnion({', '.join(parts)})"
    return "ValueRangeConstraint(0, 2147483647)"


def _range_expr(ranges: list[Any], constructor: str) -> str:
    if not ranges:
        return f"{constructor}(0, 2147483647)"
    if len(ranges) == 1:
        pair = ranges[0]
        lo = _bound_str(pair[0])
        hi = _bound_str(pair[1])
        return f"{constructor}({lo}, {hi})"
    parts = [f"{constructor}({_bound_str(r[0])}, {_bound_str(r[1])})" for r in ranges]
    return f"ConstraintsUnion({', '.join(parts)})"


def _bound_str(val: Any) -> str:
    if val == "MIN":
        return "0"
    if val == "MAX":
        return "2147483647"
    return str(val)


# ---------------------------------------------------------------------------
# Formatter class
# ---------------------------------------------------------------------------


def _member_module(member_name: str, this_module: str, name_to_mod: dict[str, str]) -> str:
    """Return the source module for a notification member symbol."""
    return name_to_mod.get(member_name, this_module)


def _make_env() -> Environment:
    env = Environment(loader=BaseLoader(), keep_trailing_newline=True)
    env.filters["pyid"] = _pyid
    env.filters["oid_tuple"] = _oid_tuple
    env.filters["pysnmp_class_for_type"] = _pysnmp_class_for_type
    env.filters["pysnmp_syntax"] = _pysnmp_syntax
    env.filters["map_pysnmp_assign"] = _map_pysnmp_assign
    env.filters["pysnmp_syntax_class"] = _pysnmp_syntax_class
    env.filters["tc_subtypespec"] = _tc_subtypespec
    env.filters["member_module"] = _member_module
    return env


class PysnmpFormatter:
    """Renders a MibModule as a pysnmp-compatible Python module."""

    FILE_SUFFIX = ".py"

    def __init__(self, no_texts: bool = False) -> None:
        self._env = _make_env()
        self._tmpl = self._env.from_string(_TEMPLATE)
        self._no_texts = no_texts

    def format(self, module: MibModule) -> str:  # noqa: A003
        # First pass: build MibTable / MibTableRow map keyed by absolute OID path.
        oid_to_class: dict[tuple[int, ...], str] = {}
        for obj in module.objects.values():
            if obj.object_type == "OBJECT-TYPE" and obj.oid_path:
                cls = _pysnmp_obj_class(obj, module)
                oid_to_class[tuple(obj.oid_path)] = cls

        # Second pass: full classification including MibTableColumn.
        objects_with_class = [
            (name, obj, _pysnmp_obj_class(obj, module, oid_to_class))
            for name, obj in module.objects.items()
            if obj.object_type == "OBJECT-TYPE"
        ]

        return self._tmpl.render(
            module=module,
            objects_with_class=objects_with_class,
            no_texts=self._no_texts,
            name_to_mod=module.import_reverse_map(),
        )
