"""pysnmp output formatter.

Generates a Python module that can be loaded by pysnmp\'s MibBuilder.
The output closely follows the format used by pysmi-compiled MIBs:

    mibBuilder.importSymbols(\'SNMPv2-SMI\', \'ModuleIdentity\', ...)
    ifMIB = ModuleIdentity((1, 3, 6, 1, 2, 1, 31,))
    mibBuilder.exportSymbols(\'IF-MIB\', **{'ifMIB': ifMIB, ...})

Limitations (out of scope for this iteration):
- TEXTUAL-CONVENTION constraints are not fully emitted.
- NOTIFICATION-TYPE OBJECTS list is omitted.
- SEQUENCE / CHOICE types generate a placeholder.
These are annotated with TODO comments in the output.

Output file: {output_dir}/{ModuleName}.py
"""
from __future__ import annotations

from jinja2 import Environment, BaseLoader

from trishul_smi.models.mib_module import MibModule
from trishul_smi.models.mib_object import MibObject
from trishul_smi.models.mib_type import MibType


# ---------------------------------------------------------------------------
# Jinja2 template
# ---------------------------------------------------------------------------

_TEMPLATE = """\
# {{ module.name }} MIB module
# Generated by trishul-smi  —  do not edit by hand.
# Source dialect: {{ module.language }}

from pysnmp.smi.builder import MibBuilder

mibBuilder = MibBuilder()

# --- Imports -----------------------------------------------------------
{% for from_module, symbols in module.imports.items() %}
{{ symbols | map_pysnmp_assign(from_module) }}
{% endfor %}

# --- MODULE-IDENTITY / OBJECT-IDENTITY --------------------------------
{% for name, obj in module.objects.items() if obj.object_type in (
       'MODULE-IDENTITY', 'OBJECT-IDENTITY', 'OBJECT IDENTIFIER') %}
{{ name | pyid }} = {{ obj.object_type | pysnmp_class }}(
    {{ obj.oid_path | oid_tuple }}
)
{% if obj.status %}if mibBuilder.loadTexts: {{ name | pyid }}.setStatus('{{ obj.status }}')
{% endif %}
{% if obj.description %}if mibBuilder.loadTexts: {{ name | pyid }}.setDescription(
    """{{ obj.description | indent(4) }}"""
)
{% endif %}
{% endfor %}

# --- OBJECT-TYPE ------------------------------------------------------
{% for name, obj in module.objects.items() if obj.object_type == 'OBJECT-TYPE' %}
{{ name | pyid }} = {{ obj.object_type | pysnmp_class }}(
    {{ obj.oid_path | oid_tuple }},
    {{ obj.syntax | pysnmp_syntax }}
).setMaxAccess('{{ obj.max_access or 'read-only' }}')
{% if obj.status %}if mibBuilder.loadTexts: {{ name | pyid }}.setStatus('{{ obj.status }}')
{% endif %}
{% if obj.description %}if mibBuilder.loadTexts: {{ name | pyid }}.setDescription(
    """{{ obj.description | indent(4) }}"""
)
{% endif %}
{% endfor %}

# --- NOTIFICATION-TYPE ------------------------------------------------
{% for name, notif in module.notifications.items() %}
{{ name | pyid }} = NotificationType(
    {{ notif.oid_path | oid_tuple }}
)  # TODO: add .setObjects() from OBJECTS clause
{% if notif.status %}if mibBuilder.loadTexts: {{ name | pyid }}.setStatus('{{ notif.status }}')
{% endif %}
{% endfor %}

# --- TEXTUAL-CONVENTION -----------------------------------------------
{% for name, tc in module.types.items() %}
{{ name }} = TextualConvention  # base: {{ tc.base_type }}
# TODO: emit full TC definition (DisplayHint, constraints)
{% endfor %}

# --- Export -----------------------------------------------------------
mibBuilder.exportSymbols(
    '{{ module.name }}',
{% for name in module.objects %}    **{'{{ name }}': {{ name | pyid }}},
{% endfor %}
{% for name in module.types %}    **{'{{ name }}': {{ name }}},
{% endfor %}
)
"""

# ---------------------------------------------------------------------------
# Jinja2 filters
# ---------------------------------------------------------------------------

_PYSNMP_CLASS = {
    "MODULE-IDENTITY":  "ModuleIdentity",
    "OBJECT-IDENTITY":  "ObjectIdentity",
    "OBJECT IDENTIFIER": "MibIdentifier",
    "OBJECT-TYPE":      "MibScalar",      # overridden per-object if columnar
    "NOTIFICATION-TYPE": "NotificationType",
    "TRAP-TYPE":        "NotificationType",
}

_PYSNMP_SYNTAX = {
    "INTEGER":           "Integer32()",
    "Integer32":         "Integer32()",
    "OCTET STRING":      "OctetString()",
    "OBJECT IDENTIFIER": "ObjectIdentifier()",
    "IpAddress":         "IpAddress()",
    "Counter32":         "Counter32()",
    "Counter64":         "Counter64()",
    "Gauge32":           "Gauge32()",
    "Unsigned32":        "Unsigned32()",
    "TimeTicks":         "TimeTicks()",
    "Opaque":            "Opaque()",
    "BITS":              "Bits()",
}


def _pyid(name: str) -> str:
    """Convert a MIB identifier to a valid Python identifier.
    Hyphens are not valid in Python; replace with underscores."""
    return name.replace("-", "_")


def _oid_tuple(oid_path: list[int]) -> str:
    if not oid_path:
        return "()"
    return "(" + ", ".join(str(n) for n in oid_path) + ",)"


def _pysnmp_class(object_type: str) -> str:
    return _PYSNMP_CLASS.get(object_type, "MibScalar")


def _pysnmp_syntax(syntax: str | None) -> str:
    if not syntax:
        return "OctetString()  # unknown syntax"
    return _PYSNMP_SYNTAX.get(syntax, f"{syntax}()")


def _map_pysnmp_assign(symbols: list[str], from_module: str) -> str:
    """Render: ( Sym1, Sym2, ) = mibBuilder.importSymbols('MOD', 'Sym1', 'Sym2')"""
    if not symbols:
        return ""
    sym_py = ", ".join(_pyid(s) for s in symbols)
    sym_str = ", ".join(f"'{s}'" for s in symbols)
    return f"( {sym_py}, ) = mibBuilder.importSymbols('{from_module}', {sym_str})"


# ---------------------------------------------------------------------------
# Formatter class
# ---------------------------------------------------------------------------

def _make_env() -> Environment:
    env = Environment(loader=BaseLoader(), keep_trailing_newline=True)
    env.filters["pyid"] = _pyid
    env.filters["oid_tuple"] = _oid_tuple
    env.filters["pysnmp_class"] = _pysnmp_class
    env.filters["pysnmp_syntax"] = _pysnmp_syntax
    env.filters["map_pysnmp_assign"] = _map_pysnmp_assign
    return env


class PysnmpFormatter:
    """Renders a MibModule as a pysnmp-compatible Python module."""

    FILE_SUFFIX = ".py"

    def __init__(self) -> None:
        self._env = _make_env()
        self._tmpl = self._env.from_string(_TEMPLATE)

    def format(self, module: MibModule) -> str:
        return self._tmpl.render(module=module)
